version: '3.8'

services:
  cassandra-node1:
    image: cassandra:4.1
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      - cassandra_net
    ports:
      - "9042:9042"

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    depends_on:
      - cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      - cassandra_net

  cassandra-node3:
    image: cassandra:4.1
    container_name: cassandra-node3
    depends_on:
      - cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      - cassandra_net

networks:
  cassandra_net:
    driver: bridge